### ISSUE TITLE
default dashboard does not use correct metrics

### ISSUE THREAD

**Issue by vkruoso** [moleculerjs/moleculer-metrics#51]
It seems like the default metrics generated for registry are like `moleculer_registry_*`, when the default dashboard uses different metrics. Also, some places where it uses `_req_` the metrics are `_request_`.

**Comment by intech** [comment]
It is best to build your dashboard based on metrics from the [documentation](https://moleculer.services/docs/0.14/metrics.html#Built-in-Internal-Metrics). Moleculer is not a dashboard contributor for different systems, and it's all in the hands of the community. Please submit a PR to this repository if you want to share your dashboard.

**Comment by vkruoso** [comment]
Sure, I intend to submit a PR to fix the dashboard here. The issue was mostly due to the fact that the collected metrics does not match the dashboard here, so it does not work out of the box and may be confusing.

**Comment by icebob** [comment]
The dashboard in this repo works with these "old" metrics modules. But in Moleculer 0.14 the built-in tracing has different metrics names and it's not compatible with this old dashboard. [This dashboard](https://github.com/icebob/kantab/blob/master/monitoring/grafana/provisioning/dashboards/Moleculer_Dashboard.json) is compatible with 0.14 metrics.

**Comment by vkruoso** [comment]
@icebob thanks for the update. Was not aware of that change. Your dashboard is great, thanks for the link!
